### ISSUE TITLE
Not working on Win 7

### ISSUE THREAD

**Issue by DavidBerkut** [barryballantines/BarrysBlackBox#2]
The application is not working on my PC. I can connect it to FG and my VA and that 's it.  

When I click on Start Recording,simply nothing happens. Also,on the bottom,there are Start-Up and Shut-Down buttons,only Shut Down button is clickable,but again,it does nothing.

Is there any way to make this work? Please

**Comment by mbuse** [comment]
Hi David,
I am running Barry's Blackbox on Windows 7 Professional, using Java JDK 1.8. and everything works as expected. I suppose that the problem is related to the Java version. So could you please check which version of Java you are using? Java 7 or 8, JDK or JRE?

Barry's Blackbox is using an API for creating Dialogs which is only available in newer JDK versions...
To verify this, you might also start the Blackbox with Logging activated.

Therefore please create a file called logging.properties with the following content:

# --- File starts here

handlers=java.util.logging.FileHandler
.level=INFO

java.util.logging.FileHandler.pattern=./log/blackbox%g.log
java.util.logging.FileHandler.limit=500000
java.util.logging.FileHandler.count=10
java.util.logging.FileHandler.level=INFO
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tc %2$s%n%4$s: %5$s%6$s%n

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

ballantines.avionics.blackbox.log.level=INFO

# --- File ends here

Run the blackbox with the following command (assuming that the properties-file and the blackbox jar is in the folder C:\blackbox)
java -Djava.util.logging.config.file=C:/blackbox/logging.properties -jar .C:/blackbox/blackbox-1.3.jar 

There should be a Java Exception with a stacktrace in your log file, if you click the Start-Recording button...

Please send me the log file.

**Comment by DavidBerkut** [comment]
The older 0.8 version works,sort of. On the EVA web site,the ACARS map is
showing the distance of 2000+ nm ,even for the flight of just 100. Seems
like the application is barely connected to the VA ,but really well
connected to the FGFS.

Can u help with that?

Thaaaanks a lot.

Cheers

2016-03-28 21:16 GMT+02:00 Matthias Buse notifications@github.com:

**Comment by mbuse** [comment]
Hi David,
what Java version are you running? is it a JDK or a Java Runtime Environment (JRE). The support of Dialogs was added between Blackbox version 1.0 and 1.1, since then Java 1.8 is required. If the 0.8 version is running on your machine, I would guess, you are using Java. 1.7... can you verify this?

About the distances in the ACARS map: I observed a similar problem, but it seems to be related to the newer Flightgear versions. If no runway has been set in the FG Route Manager for the destination airport, FG calculates a wrong (much to long) distance for the route. (You can check the FG internal map to verify that there is a very long leg added between the last waypoint and the destination airport). Barrys Blackbox just reads the distances from FG and that might be the reason why your distance ist shown incorrectly...
... Setting a arrival runway for your destination in FG Route Manager should solve the problem.

Fingers crossed!

**Comment by mbuse** [comment]
Probably this issue is also related to some changes in the implementation of JavaFX. Release 1.4 should fix it...
